
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import tkinter as tk
from tkinter import messagebox
import subprocess



OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\MENDOZA,BUSTERO_GYM_PROG\MENDOZA_BUSTERO_GYM_LOG\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = tk.Tk()

window.geometry("900x700")
window.configure(bg = "#000000")

def validate_login():
    global username_entry, password_entry  

    userid = username_entry.get()
    password = password_entry.get()

    # You can add your own validation logic here
    if userid == "admin" and password == "admin":
    
        messagebox.showinfo("Notice","Successfully logged in")
        window.destroy()  

        subprocess.run(['python', 'gymLogApp.py'])
    else:
        messagebox.showerror("Login Failed", "Invalid username or password")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 700,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    644.0,
    375.5,
    image=entry_image_1
)
username_entry = Entry(
    bd=0,
    bg="#E4E4E4",
    fg="#000716",
    highlightthickness=0
)
username_entry.place(
    x=517.0,
    y=358.0,
    width=254.0,
    height=33.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    647.0,
    458.5,
    image=entry_image_2
)
password_entry = Entry(
    bd=0,
    bg="#E4E4E4",
    fg="#000716",
    highlightthickness=0
)
password_entry.place(
    x=520.0,
    y=441.0,
    width=254.0,
    height=33.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=validate_login,
    relief="flat"
)
button_1.place(
    x=520.0880126953125,
    y=509.415283203125,
    width=253.05484008789062,
    height=45.58473205566406
)

canvas.create_text(
    517.0,
    333.0,
    anchor="nw",
    text="Username:",
    fill="#C7C7C7",
    font=("Inter Bold", 14 * -1)
)

canvas.create_text(
    520.0,
    415.0,
    anchor="nw",
    text="Password:",
    fill="#C7C7C7",
    font=("Inter Bold", 14 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    647.0,
    227.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    200.0,
    350.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
